---
apiVersion: v1
kind: Service
metadata:
  name: education-provider-registry-integration-API-maintenance
spec:
  selector:
    app: education-provider-registry-integration-API-maintenance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
